### ISSUE TITLE
关于 OpenCV

### ISSUE THREAD

**Issue by lilydjwg** [xuwd1/wemeet-wayland-screenshare#1]
你试过用 dlopen（`RTLD_LOCAL`）来加载 opencv 库吗？虽然没看到崩溃细节，但我怀疑是符号冲突，那么 RTLD_LOCAL 应当能避免。

**Comment by xuwd1** [comment]
好主意，感谢建议，我今日会试一下. 之前使用的方法都是在cmake中链接opencv.

**Comment by xuwd1** [comment]
本项目现在已经根据提议实现了对opencv库的动态加载. 得益于此，现在本项目中的图像缩放可以确保aspect ratio正确了，感谢提议！
