### ISSUE TITLE
Failed to create screencast session: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: Unavailable cursor mode 1

### ISSUE THREAD

**Issue by Corybyte** [xuwd1/wemeet-wayland-screenshare#12]
ArchLinux + Hyprland 0.45.0

通过yay 安装了 wemeet-wayland-screenshare-git 包之后，手动在bash中执行了 wemeet-wayland-screenshare
显示出 Failed to create screencast session: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: Unavailable cursor mode 1
且并没有显示出README,md 中步骤三的提示框

**Comment by xuwd1** [comment]
看起来是hyprland上不支持最新的cursor fix. 请先手动checkout commit `7501180534` 本地编译使用. 麻烦提供一下完整的命令行输出，以及环境变量`XDG_SESSION_DESKTOP`的值. 我会尽快做一个单独的分支尝试修复.

**Comment by xuwd1** [comment]
nvm，已经修复并且在本地环境验证过，请使用`yay -S --rebuild --refresh`重新安装最新版本。

**Comment by Corybyte** [comment]
已成功解决，谢谢
