### ISSUE TITLE
有没有考虑过 xwayland-video-bridge 这种方式?

### ISSUE THREAD

**Issue by ihipop** [xuwd1/wemeet-wayland-screenshare#2]
https://www.gamingonlinux.com/2023/03/xwayland-video-bridge-created-to-improve-linux-screen-sharing/

当然因为 wemeet强制画图,默认 xwayland-video-bridge 也没法和 wemeet适配

**Comment by xuwd1** [comment]
你好，感谢提议，但当前不考虑利用xwaylandvideobridge. 这里的主要原因是，一方面，xwaylandvideobridge是kde专有功能，尽管该项目当前值确定kde上可用，但希望仍然保留兼容GNOME的可能性. 另一方面，给wemeetapp上hook强迫其使用xwaylandvideobridge的工作量个人认为和现有代码功能重叠且工作量相仿，个人认为没有必要.
