### ISSUE TITLE
Possibly better compatibility using gstreamer

### ISSUE THREAD

**Issue by DerryAlex** [xuwd1/wemeet-wayland-screenshare#3]
Pipewire 官方提供了一个 `pipewiresrc` 的 gstreamer 插件，这可以和 wireplumber 以及 GNOME 上工作。(参考 [`xdp-screen-cast.py`](https://gitlab.gnome.org/-/snippets/19)) 同时， gstreamer 有一个 `ximagesink` 插件，其调用 `XShmAttach` 和 `XShmPutImage`。一个想法是通过 gstreamer 建立一个类似 `pipewiresrc ! videoconvert ! ximagesink` 的 pipeline, 然后劫持 `XShmPutImage` 来获取图像。

**Comment by xuwd1** [comment]
你好，谢谢提议，但由于我几乎对gstreamer一无所知，关于提议内容还有些具体的问题：
1. 提议中构想的方式是否是一种全新的，完全异步的图像填充pipeline？更具体而言，提议所设想的过程是否是：`XShmAttach`启动某个异步的程序（`pipewiresrc ! videoconvert ! ximagesink`），随后由这个程序完全异步地向wemeet所希望获取的`XImage`填充图像，最后在`XShmDetach`贝调用后杀死这个异步程序？如果是这样的话，听起来其改动量值得完全新建一个本项目的GNOME/Gstreamer版本.
2. 更进一步地，提议中提出的设想是否有可能整合到现有实现中？

**Comment by DerryAlex** [comment]
确实单独实现可能会更好一些。等我有时间了研究一下
