### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Bryan2333** [xuwd1/wemeet-wayland-screenshare#7]
我用的是Arch Linux，桌面环境是KDE Plasma。

wemeet-wayland-screenshare无法启动，终端里面报错
```
/bin/sh: symbol lookup error: /usr/lib/wemeet/libhook.so: undefined symbol: XRRGetOutputInfo
```

**Comment by xuwd1** [comment]
请确保安装了xrandr，aur包那边会很快更新depends

**Comment by Bryan2333** [comment]
我这边确认了一下，我电脑是安装了libxrandr的了，但是仍然无法启动
![image](https://github.com/user-attachments/assets/c7d31d72-4f4b-46f0-b94b-473c34ed70fd)

**Comment by xuwd1** [comment]
已经更新了一个commit尝试修复此问题，请手动build测试下.

**Comment by Bryan2333** [comment]
我测试了一下，没问题了。
